---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
   podSubnet: 10.244.0.0/16
   serviceSubnet: 10.96.0.0/16
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
   podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
   serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.100.0.1"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 10.100.0.2,fd00:1:2:3::2
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
   bootstrapToken:
      apiServerEndpoint: 10.100.0.1:6443
      token: tokenvalue123
      caCertHashes:
      - sha256:sha256value
# change auth info above to match the actual token and CA certificate hash for your cluster
nodeRegistration:
   kubeletExtraArgs:
      node-ip: 10.100.0.3,fd00:1:2:3::3
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
controlPlane:
   localAPIEndpoint:
      advertiseAddress: 10.100.0.2
      bindPort: 6443
discovery:
   bootstrapToken:
      apiServerEndpoint: 10.100.0.1:6443
      token: tokenvalue2
      caCertHashes:
      - sha256:sha256avalue2
# change auth info above to match the actual token and CA certificate hash for your cluster
nodeRegistration:
   kubeletExtraArgs:
      node-ip: 10.100.0.4,fd00:1:2:3::4

