apiVersion: v1
kind: Pod
metadata:
   name: nginx
spec:
   containers:
   -  name: nginx
      image: nginx:1.14.2
      env:
      -  name: myname
         value: itsname
      -  name: whoami
         value: whatiam
      -  name: fromcm
         valueFrom:
            configMapKeyRef:
               name: cm2
               key: mykey1
      -  name: fromsecret
         valueFrom:
            secretKeyRef:
               name: cm2
               key: mykey1
      -  name: MY_POD_NAME
         valueFrom:
            fieldRef:
               fieldPath: metadata.name
      envFrom:
      -  configMapRef:
            name: cm1
      -  secretRef:
            name: secret1

      ports:
      -  name: mycontainerPort
         containerPort: 80
