apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: persistence
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
     storage: 256Mi
