apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-combined
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.cka.cncf.com/aggregate: "true"
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dep-modify
  labels:
    rbac.cka.cncf.com/aggregate: "true"
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create","delete","patch","update"]
