title: Raman Knowledge Park
email: venkataramant@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/docs/" # the subpath of your site, e.g. /blog
url: "https://github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  venkataramant@gmail.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

remote_theme: zendesk/jekyll-theme-zendesk-garden@main

lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge