apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
   name: my-csr
spec:
   request: <<base64 of csr file>>
   signerName: kubernetes.io/kube-apiserver-client
   usages:
   - client auth
