apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: persistence
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/db
