apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: persistence
spec:
 storageClassName: "example-nfs"
 resources:
   requests:
    storage: 10Mi
 accessModes:
   - ReadWriteMany
