apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: tvr-service-view
   namespace: development
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: service-view
subjects:
-  kind: User
   name: tvr
   apiGroup: rbac.authorization.k8s.io
